apiVersion: v1
kind: Service
metadata:
  name: hello-world-clusterip
  labels:
    app: hello-world
    environment: learning
spec:
  type: ClusterIP
  selector:
    app: hello-world
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP