apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app: hello-world
    environment: learning
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  sessionAffinity: None 